# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: car_management
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#    ports:
#      - '15432:5432'
